In [3]:
import pandas as pd
import os
import datetime as dt
os.getcwd()

'/Users/aaronnguyen/Documents/PersonalProjects/capital_vision/notebooks'

In [29]:
self_data = pd.read_csv('../dashboard/models/asx200_data.csv', index_col=0)

In [30]:
self_data.head()

                 metrics     value code        rp_type  report_year
0         earning_assets       NaN  ANZ  balance_sheet         2014
1       short_term_money   22708.0  ANZ  balance_sheet         2014
2  investment_securities  128621.0  ANZ  balance_sheet         2014
3         due_from_banks       0.0  ANZ  balance_sheet         2014
4                  loans  521752.0  ANZ  balance_sheet         2014

In [10]:
import pandas as pd

FILE_PATH = "../dashboard/models/asx200_data.csv"

class FinancialMetrics:
    def __init__(self):
        self.data = (
            pd.read_csv(FILE_PATH, index_col=0)
            .sort_values(by="report_year", ascending=False)
        )

    def symbol(self, symbol):
        self.symbol = symbol
        return self

    def get_fin_metrics(self, metrics, y_range):
        res_df = self.data.sort_values(by="report_year", ascending=False)
        query_years = self.data.query("code == @self.symbol")["report_year"].unique()[
            :5
        ]
        res_df = self.data.query(f''' \
                    code == @self.symbol and \
                    report_year in @query_years and \
                    metrics in @metrics
                ''')
        return res_df

In [15]:
metrics = [
    'net_investing_cash_flow',
    'net_financing_cash_flow',
    'net_operating_cash_flow',
    'cash_at_end_of_period', 
    'cash_at_beginning_of_period', 
]
y_range = 5
symbol = 'WOW'

stock = FinancialMetrics().symbol('BHP').get_fin_metrics(metrics, y_range)

In [16]:
stock

                           metrics      value code    rp_type  report_year
65072      net_operating_cash_flow   28206.64  BHP  cash_flow         2023
65083      net_investing_cash_flow  -19705.88  BHP  cash_flow         2023
65090      net_financing_cash_flow  -15558.07  BHP  cash_flow         2023
65092  cash_at_beginning_of_period   25996.98  BHP  cash_flow         2023
65094        cash_at_end_of_period   18737.56  BHP  cash_flow         2023
65063        cash_at_end_of_period    25019.6  BHP  cash_flow         2022
65061  cash_at_beginning_of_period   22130.93  BHP  cash_flow         2022
65059      net_financing_cash_flow  -33048.34  BHP  cash_flow         2022
65052      net_investing_cash_flow  -10101.61  BHP  cash_flow         2022
65041      net_operating_cash_flow   46703.44  BHP  cash_flow         2022
65021      net_investing_cash_flow  -10434.96  BHP  cash_flow         2021
65010      net_operating_cash_flow   36225.06  BHP  cash_flow         2021
65028      net_financing_cash_flow  -23838.79  BHP  cash_flow         2021
65032        cash_at_end_of_period   20279.33  BHP  cash_flow         2021
65030  cash_at_beginning_of_period   17858.47  BHP  cash_flow         2021
65001        cash_at_end_of_period   19562.87  BHP  cash_flow         2020
64997      net_financing_cash_flow  -14209.53  BHP  cash_flow         2020
64990      net_investing_cash_flow  -11097.19  BHP  cash_flow         2020
64999  cash_at_beginning_of_period   22720.38  BHP  cash_flow         2020
64979      net_operating_cash_flow   22885.04  BHP  cash_flow         2020
64970        cash_at_end_of_period   22234.42  BHP  cash_flow         2019
64968  cash_at_beginning_of_period   22548.12  BHP  cash_flow         2019
64966      net_financing_cash_flow  -29271.35  BHP  cash_flow         2019
64959      net_investing_cash_flow    3717.38  BHP  cash_flow         2019
64948      net_operating_cash_flow   25482.68  BHP  cash_flow         2019